name : python lambda test

on:
  push:
    branches: [ main ]
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: test python lambda
      run: |
        cd unittest
        pip install pytest
        pytest test_view_count_neelaupa_table.py